name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run Cargo Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      name: Checkout code
    - name: Run Build
      run: cargo build --verbose
  clippy:
    name: Check Cargo Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      name: Checkout code
    - name: Run Clippy
      run: cargo clippy --verbose -- -D warnings
  test:
    name: Run Cargo Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      name: Checkout code
    - name: Run Tests
      run: cargo test t_ --verbose