name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    name: Ubuntu Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - name: Install gtk and pkgconfig
        run: sudo apt-get install -y libgtk2.0-dev pkgconfig
      - name: Run Build
        run: cargo build --verbose
  build-windows:
    name: Windows Cargo Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - name: Run Build
        run: cargo build --verbose
  clippy-ubuntu:
    name: Ubuntu Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - name: Install gtk and pkgconfig
        run: sudo apt-get install -y libgtk2.0-dev pkgconfig
      - name: Run Clippy
        run: cargo clippy --verbose -- -D warnings

  clippy-windows:
    name: Windows Cargo Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - name: Run Clippy
        run: cargo clippy --verbose -- -D warnings

  test-ubuntu:
    name: Ubuntu Cargo Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - name: Install gtk and pkgconfig
        run: sudo apt-get install -y libgtk2.0-dev pkgconfig
      - name: Run Tests
        run: cargo test t_ --verbose
  test-windows:
    name: Windows Cargo Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - name: Run Tests
        run: cargo test t_ --verbose
